### ISSUE TITLE
Not compatible with Neos 4.0

### ISSUE THREAD

**Issue by simonschaufi** [jonnitto/Carbon.Compression#1]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Version: any
* Platform/Target and Browser Versions: any

### What you did
Upgrade to Neos 4.0

### Expected Behavior
Upgrade works with this package enabled

### Actual Behavior
`carbon/compression` is not compatible with Neos 4.0
```
carbon/compression 1.0.3 requires neos/neos ~3.0
```

**Comment by jonnitto** [comment]
I'll test all my plugins this weekend. Sorry for that, my wife is a bit sick and with a 7 month old baby is it not that easy

**Comment by simonschaufi** [comment]
Thank you. No hurry ;)

**Comment by jonnitto** [comment]
Was an easy one ;-) Solved with [1.1.0](https://github.com/jonnitto/Carbon.Compression/releases/tag/1.1.0)
